title: HERWEARS.ID
description: Gaya modern, nyaman digunakan.
logo: /assets/images/himwears.png
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://herwears.pages.dev"
twitter_username: jekyllrb
github_username: jekyll

# Build settings
plugins:
  - jekyll-feed

collections:
  collections:
    output: true
    permalink: /collection/:name/
  outfits:
    output: true
    permalink: /outfits/:name/
